name: botecoPro
description: "GestÃ£o completa para seu bar"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_animate: ^4.0.0
  flutter_launcher_icons: 0.14.3
  table_calendar: ^3.0.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.0
  intl: ^0.18.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: 2.3.2
  path_provider: 2.1.4
  provider: 6.1.2
  http: '>=1.0.0'
  uuid: '>=3.0.0'

  dio: any
  flutter_secure_storage: any
  google_sign_in: any
  jwt_decode: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
