name: botecoPro
description: "Boteco PRO - GestÃ£o Completa para o seu bar!"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_animate: ^4.0.0
  flutter_launcher_icons: 0.14.3
  table_calendar: ^3.0.0
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.0
  intl: ^0.20.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: ^0.71.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  provider: ^6.1.4
  http: '>=1.0.0'
  uuid: '>=3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
